label = "Apical Constriction"

cell_prop = { }
parameter_ranges = [ ]
seeds_per_config = 20

[metadata]
model = "EHT"
version = "1.5.0"

[general]
t_end = 54
dt = 0.1
random_seed = 0
full_circle = false
w_init = 10
h_init = 8
mu = 0.2
n_substeps = 40
alg_dt = 0.05
w_screen = 15
h_screen = 0
p_div_out = 0.8
perimeter = 20
aspect_ratio = 0
hard_sphere_nuclei = false

  [[general.default_events]]
  type = "special"
  id = "default_cell_division"
  name = "Cell Division"
  start = 0
  end = inf
  period = 0
  probability = "p_div_out"
  cell_cycle_phase = "division"
  special_name = "cell_division"

  [[general.default_events]]
  type = "special"
  id = "default_cell_cycle_reset"
  name = "Cell Cycle Reset"
  start = 0
  end = inf
  period = 0
  probability = "1"
  cell_cycle_phase = "division"
  special_name = "cell_cycle_reset"

  [[general.default_events]]
  type = "parameter_change"
  id = "default_stiffness_apical_apical_g2"
  name = "Apical Stiffness (G2)"
  start = 0
  end = 0
  period = 0
  probability = "1"
  cell_cycle_phase = "g2"
  target_parameter = "stiffness_apical_apical"
  formula = "stiffness_apical_apical_div"

  [[general.default_events]]
  type = "parameter_change"
  id = "default_R_hard_mitosis"
  name = "R_hard (Mitosis)"
  start = 0
  end = 0
  period = 0
  probability = "1"
  cell_cycle_phase = "mitosis"
  target_parameter = "R_hard"
  formula = "R_hard_div"

  [[general.default_events]]
  type = "parameter_change"
  id = "inm_contract_apical"
  name = "INM: Contract Apical"
  start = 0
  end = 0
  period = 0
  probability = "INM"
  cell_cycle_phase = "g2"
  target_parameter = "apical_cytos_strain"
  formula = "-1"

  [[general.default_events]]
  type = "parameter_change"
  id = "inm_extend_basal"
  name = "INM: Extend Basal"
  start = 0
  end = 0
  period = 0
  probability = "1"
  prereq = "inm_contract_apical"
  cell_cycle_phase = "g2"
  target_parameter = "basal_cytos_strain"
  formula = "2"

[cell_types.control]
N_init = 40
location = ""
R_hard = 0.3
R_hard_div = 0.7
R_soft = 1
dur_G2 = 0.5
dur_mitosis = 0.5
k_apical_junction = 1
k_cytos = 5
max_cytoskeleton_length = 0
run = 0
running_speed = 1
running_mode = 0
stiffness_apical_apical = 5
stiffness_apical_apical_div = 10
stiffness_nuclei_apical = 2
stiffness_nuclei_basal = 2
stiffness_repulsion = 1
stiffness_straightness = 15
lifespan_start = 10
lifespan_end = 21
INM = 1
hetero = false
events_v2 = [ ]
apical_cytos_strain_init = 0
basal_cytos_strain_init = 0
skip_default_events = [ ]
diffusion = 0.1
basal_damping_ratio = 1
max_basal_junction_dist = 0.666666666666666
cytos_init = 1.5
basal_membrane_repulsion = 0
apical_junction_init = 0.333333333333333

  [cell_types.control.color]
  r = 0
  g = 128
  b = 0


[cell_types.emt]
N_init = 10
location = "bottom"
R_hard = 0.3
R_hard_div = 0.7
R_soft = 1
dur_G2 = 0.5
dur_mitosis = 0.5
k_apical_junction = 1
k_cytos = 5
max_cytoskeleton_length = 0
run = 0
running_speed = 1
running_mode = 0
stiffness_apical_apical = 5
stiffness_apical_apical_div = 10
stiffness_nuclei_apical = 2
stiffness_nuclei_basal = 2
stiffness_repulsion = 1
stiffness_straightness = 15
lifespan_start = 10
lifespan_end = 21
INM = 1
hetero = false
apical_cytos_strain_init = 0
basal_cytos_strain_init = 0
skip_default_events = [ "default_cell_division" ]
diffusion = 0.1
basal_damping_ratio = 1
max_basal_junction_dist = 0.666666666666666
cytos_init = 1.5
basal_membrane_repulsion = 0
apical_junction_init = 0.333333333333333

  [cell_types.emt.color]
  r = 255
  g = 0
  b = 255


  [[cell_types.emt.events_v2]]
  type = "parameter_change"
  id = "activate_apical_constriction"
  name = "Activate Apical Constriction"
  start = 3
  end = 5
  period = 0
  probability = "1"
  cell_cycle_phase = "any"
  special_name = "lose_apical_adhesion"
  target_parameter = "k_apical_junction"
  formula = "10"

  [[cell_types.emt.events_v2]]
  id = "activate_apical_constriction_2"
  name = "Activate Apical Constriction (2)"
  start = 3
  end = 5
  period = 0
  probability = "1"
  cell_cycle_phase = "any"
  type = "parameter_change"
  target_parameter = "stiffness_apical_apical"
  formula = "old_value * 4"

  [[cell_types.emt.events_v2]]
  type = "special"
  id = "lose_basal"
  name = "Lose Basal Adhesion"
  start = 3
  end = 5
  period = 0
  probability = "0.7"
  cell_cycle_phase = "any"
  special_name = "lose_basal_adhesion"

[time_samples]
start = 0
end = 48
step = 12
